export const APIEndpoints = {
  logIn: '/auth/login',
  forgotPassWord: '/change/pass',
  getAllDiselRequisition: '/mechanic/diselrequisition',
  createDiselRequisition: '/mechanic/diselrequisition',
  getAllDiselRequisitionByUserId: '/mechanic/diselrequisition/getByCreator',
  getAllDiselReceipt: '/mechanic/diselreceipt',
  getAllDiselReceiptbyUserId: '/mechanic/diselreciept/getByCreator',
  createDiselReceipt: '/mechanic/diselreceipt',
  getDiselConsumption: '/mechanic/consumptionsheet',
  createDiselConsumption: '/mechanic/consumptionsheet',
  consumabaleItem: '/super/admin/consumableitems',
  equipments: '/super/admin/equipment/getAll',
  getAllConsumptionSheetByUserId: '/mechanic/consumptionsheet/getbycreator',
  getAllMaintananceLog: '/mechanic/maintananceSheet',
  createMaintananceLog: '/mechanic/maintenanceSheet',
  getAllMaintananceLogByUserId: '/mechanic/maintenanceSheet/byCreator',

  getProjectsByUserId: '/super/admin/employee/get/projects',
};
